version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  app:
    build: .
    container_name: redis-chat
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_ENDPOINT_URL=redis:6379   # ✅ THIS IS THE FIX
    restart: always
